config/routes.rb
Rails.application.routes.draw do

  root 'notes#index'
  devise_for :users
  resources :notes

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :note
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :note
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    @notes = Note.all
  end
  
  def show
    
  end
  
  def new
    @note=Note.new
  end
  
  def create
    @note=Note.new(note_params)
    if @note.save
        redirect_to @note
      else
        render 'new'
      end
  end
  
  def edit
    
  end
  
  def update
    if @note.update(note_params)
      redirect_to notes_path, notice: 'Successful update'
    else
      render 'edit'
    end
  end
  
  def destroy
    @note.destroy
    logger.warn("====#{@note}")
     redirect_to notes_path, notice: 'Successfully deleted'
    end
  
  private
    def find_note
      @note= Note.find(params[:id])
      end
    
    def note_params
      params.require(:note).permit(:title, :content, :date_at)
      end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_messages.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<% if !user_signed_in? %>
    <%= link_to 'Log in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
<% else %>
    <%= link_to 'Edit account', edit_user_registration_path %>
    <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteIt</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/messages' %>
<%= render 'layouts/navigation' %>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
	= f.input :title
	= f.input :content
	= f.input :date_at
	= f.button :submit

app/views/notes/edit.html.erb
<%= render 'form' %>

app/views/notes/index.html.erb
<%= link_to 'Stvori novu bilješku', new_note_path %>
<table>
<thead>
	<tr>
		<td>ID</td>
		<td>Naziv</td>
		<td>Datum</td>
		<td>Opcije</td>
	</tr>
</thead>
<tbody>
	<% @notes.each do |note| %>
		<tr>
			<td><%= note.id %></td>
<td><%= note.title %></td>
<td><%= note.date_at %></td>
<td><%= link_to "Edit", edit_note_path(note) %> | <%= link_to 'Destroy', note_path(note), method: :delete, data: {confirm: 'Jeste sigurni?'} %></td>
			</tr>
	<% end %>
</tbody>
</table>

app/views/notes/new.html.haml
%h1 Add a new note
= render 'form'

app/views/notes/show.html.haml
%h1= @note.title
%p= @note.content
%p= @note.date_at

= link_to "All Notes", notes_path